# development.yml
version: '2'
services:
  php-fpm:
    image: php71-fpm-centos68-phalcon-withext
    restart: always
    volumes:
      - /work/:/work/
      -"/work/yphp/php/etc/":/usr/local/php/etc/  \
      -"/work/yphp/nginx/conf/":/usr/local/nginx/conf/  \
      -"/work/yphp/nginx/logs/":/usr/local/nginx/logs/  \
    ports:
      - 90:9000
      - 80:80